# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCE
# ===============================
# Try to use environment variable if set (Render), otherwise fallback to localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/digital_banking?currentSchema=public&options=-c%20timezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validateOnMigrate=false
spring.flyway.cleanDisabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.repair-on-migrate=true


# ===============================
# LOGGING & ERROR
# ===============================
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.fintech.digitalbanking=DEBUG
logging.level.org.springframework.web=DEBUG

server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always
